### PR TITLE
fix(image-loader): use tempDirectory on iOS

### PR DESCRIPTION
**Pull request by swiftyone**
The tempDirectory can be accessed from the WKWebView as well; no need
for base64!

### CODE REVIEW

**Comment by swiftyone** [comment]
As the file reader is not used any more it should also fix issues #37 and #31

**Comment by ihadeed** [comment]
According to the File plugin documentation, the tempDirectory is meant for temporary files that might not persist across app restarts. I haven't played around with the `tempDirectory` enough to figure out how it works. Did you experiment with it to see if the cache persists over a few sessions at least?

What if we add an option to customize the iOS behavior, to make sure everybody is happy. Available options can be:
- `base64`: returns a base64 image
- `tempDir`: implements your solution
- `disable` disable the caching completely and return the original URL

Not sure how the new Ionic WKWebView fork updates work, but I think they serve files via `http://` protocol instead of `file:///`.

And I think the Base64 option will be helpful to develop with `ionic run <platform> --livereload`, so it might be a good idea to keep the functionality around.

**Comment by swiftyone** [comment]
In my experience the `tempDirectory` is usually persistent, I guess it is only removed if the device runs out of available space.
But I agree, it could be a good idea to keep the base64 option, even though I cannot recommend using it on a device, at least not in production.

I will implement the option next week!
Cheers!

**Comment by ihadeed** [comment]
Thanks @swiftyone

**Comment by swiftyone** [comment]
Alright, have a look at it!
Now all the files are copied to the temporary directory, if needed. This way there should be no problems with the persistence of the directory…
Also I did use readAsDataURL to avoid directly using the FileReader, which can lead to some problems (#31).

I did not(!) include the 'disable' option, as I was not completely sure, if this is really necessary; I don't really see the benefit of it.

**Comment by ihadeed** [comment]
Looks good, thanks @swiftyone !

**Pull request merged**
