### PR TITLE
Fixed Ionic 4 implementation

### LINKED ISSUE #209: Ionic 4 - plans for compatibility
Are there any plans to make Ionic Image Loader compatible with Ionic 4?

Currently it can't be used with Ionic 4 because of error:

ERROR in node_modules/ionic-image-loader/dist/providers/image-loader.d.ts(3,26): error TS2307: Cannot find module 'ionic-angular'.

### PR DESCRIPTION
**Pull request by ruudboon**
I think this fixes the Ionic 4 implementation, didn't add any unit test.
Should fix #209

### CODE REVIEW

**Comment by ihadeed** [comment]
Thanks @ruudboon 

I'm not familiar with the ng-packagr library
1. what's the pros/cons compared to compiling with `ngc`?
2. shouldn't we add `ng-packagr` as a devDependency to avoid relying on it to be globally available?

**Comment by SteveTro** [comment]
@ruudboon

Yes after removing it (it was already included some lines before ) i was able to Install it. But i cant import the module cause its Not found. Any advice in this?

**Comment by yuyinitos** [comment]
I'm using `"@ionic-native/file": "^5.0.0-beta.22",` in the package.json file and it works fine.

**Comment by SimonBigelmayr** [comment]
when will the Ionic 4 implementation be merged?

**Pull request closed without merging**
